name: Build and Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'  # 允许以 "v" 开头的标签触发自动构建

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Build project
        run: xcodebuild -project Clip.xcodeproj -scheme Clip -configuration Release build

      - name: Archive project
        run: xcodebuild -project Clip.xcodeproj -scheme Clip -configuration Release archive -archivePath $PWD/build/Clip.xcarchive

      - name: Export IPA
        run: xcodebuild -exportArchive -archivePath $PWD/build/Clip.xcarchive -exportPath $PWD/build/output -exportOptionsPlist exportOptions.plist

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/output/Clip.ipa
          asset_name: Clip.ipa
          asset_content_type: application/octet-stream
